#!/bin/python3

import math
import os
import random
import re
import sys
import itertools
from itertools import combinations

#
# Complete the 'acmTeam' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts STRING_ARRAY topic as parameter.
#

def acmTeam(topic):
    # Write your code here
    teams = list(itertools.combinations(topic, 2))
    subjects = []
    for team in teams:
        known = 0
        for topic in range(len(team[0])):
            if team[0][topic] == "1" or team[1][topic] == "1":
                known += 1
        subjects.append(known)
    return [max(subjects), subjects.count(max(subjects))]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    topic = []

    for _ in range(n):
        topic_item = input()
        topic.append(topic_item)

    result = acmTeam(topic)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
