#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    high_score=0
    low_score=0
    count_high=0
    count_low=0
    for i in range(len(scores)):
        if i==0:
            high_score=low_score=scores[i]
        elif scores[i]>high_score:
            high_score=scores[i]
            count_high+=1
        elif scores[i]<low_score:
            low_score=scores[i]
            count_low+=1
    return count_high,count_low
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
