#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalizeArray' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def equalizeArray(arr):
    # Write your code here
    l=len(arr)
    d_arr={}
    for i in arr:
        if i in d_arr:
            d_arr[i]=d_arr[i]+1 
        else:
            d_arr[i]=1 
    ma=0
    for i in arr:
        if d_arr[i]>ma:
            ma=d_arr[i] 
    return l-ma
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
