#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'extraLongFactorials' function below.
#
# The function accepts INTEGER n as parameter.
#

def extraLongFactorials(n):
    # Write your code here
    if (n==1):
        return 1
    else:
        fact=n * extraLongFactorials(n-1)
        return fact

if __name__ == '__main__':
    n = int(input().strip())

    print(extraLongFactorials(n))
