#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kaprekarNumbers' function below.
#
# The function accepts following parameters:
#  1. INTEGER p
#  2. INTEGER q
#

def kaprekarNumbers(p, q):
    # Write your code here
    m=[]
    for i in range(p,q+1):
        sq=str(i**2)
        if(len(sq)>1):
            if(int(sq[:len(sq)//2])+int(sq[len(sq)//2:])==i):
                m.append(str(i)) 
        elif(i==1):
            m.append(str(i))
    print(" ".join(m) if m != [] else "INVALID RANGE") 

if __name__ == '__main__':
    p = int(input().strip())

    q = int(input().strip())

    kaprekarNumbers(p, q)
