#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeInWords' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER h
#  2. INTEGER m
#

def timeInWords(h, m):
    # Write your code here
    word = ["one", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twenty one", "twenty two", "twenty three", "twenty four", "twenty five", "twenty six", "twenty seven", "twenty eight", "twenty nine"]
    if m == 0:
        return word[h] + " o' clock"
    elif m == 15:
        return "quarter past " + word[h]
    elif m == 30:
        return "half past " + word[h]
    elif m == 45:
        return "quarter to " + word[(h + 1) % 12]
    elif m == 1:
        return "one minute past " + word[h]
    elif m == 59:
        return "one minute to " + word[(h + 1) % 12]
    elif m < 30:
        return word[m] + " minutes past " + word[h]
    else:
        return word[60 - m] + " minutes to " + word[(h + 1) % 12]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = int(input().strip())

    m = int(input().strip())

    result = timeInWords(h, m)

    fptr.write(result + '\n')

    fptr.close()
