#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    for i in range(2):
        x=s[0]+s[1]
    if s[8]+s[9]=='PM' and int(x)!=12:
        x=str(int(x)+12)
    if s[8]+s[9]=='AM' and int(x)==12:
        x='00'
    for i in range(2,8):
        x=x+s[i]
    return x

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
